security:
  password_hashers:
    App\Entity\User: 'auto'
  
  providers:
    users:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/_(profiler|wdt)
      security: false
      
    api:
      pattern: ^/api/
      stateless: true
      provider: users
      jwt: ~

    client_login:
      pattern: ^/client/login
      stateless: true
      json_login:
        check_path: /client/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    admin_login:
      pattern: ^/admin/login
      stateless: true
      json_login:
        check_path: /admin/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

  access_control:
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/docs, roles: PUBLIC_ACCESS }
    - { path: ^/client/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin/login, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }